create table produto (
	cod_produto INT,
	nome VARCHAR(50),
	preço FLOAT
);
insert into produto (cod_produto, nome, preço) values (1, 'Espresso Brasileiro', '6.50');
insert into produto (cod_produto, nome, preço) values (2, 'Cappuccino', '8.00');
insert into produto (cod_produto, nome, preço) values (3, 'Irish Coffee', '8.00');
insert into produto (cod_produto, nome, preço) values (4, 'Latte Macchiato', '12.50');
insert into produto (cod_produto, nome, preço) values (5, 'Mocha Duplo', '12.80');
insert into produto (cod_produto, nome, preço) values (6, 'HI Especial',  '20.50');
insert into produto (cod_produto, nome, preço) values (7, 'Café Gelado', '10.00');
insert into produto (cod_produto, nome, preço) values (8, 'Café Preto', '5.00');
insert into produto (cod_produto, nome, preço) values (9, 'Café com Leite', '7.00');
insert into produto (cod_produto, nome, preço) values (10, 'Café com Avelã', '8.55');
insert into produto (cod_produto, nome, preço) values (11, 'Café Cremoso', '9.80');
insert into produto (cod_produto, nome, preço) values (12, 'Café com Canela', '7.00');
insert into produto (cod_produto, nome, preço) values (13, 'Cappuccino Italiano', '18.95');
insert into produto (cod_produto, nome, preço) values (14, 'Espresso Panna', '10.75');
insert into produto (cod_produto, nome, preço) values (15, 'Café Americano', '7.98');
insert into produto (cod_produto, nome, preço) values (16, 'Chocolate Quente', '9.00');
insert into produto (cod_produto, nome, preço) values (17, 'Leite com Caramelo', '6.90');
insert into produto (cod_produto, nome, preço) values (18, 'Suco Natural', '12.50');
insert into produto (cod_produto, nome, preço) values (19, 'Suco Industrializado', '5.00');
insert into produto (cod_produto, nome, preço) values (20, 'Água sem Gás', '4.00');
insert into produto (cod_produto, nome, preço) values (21, 'Água com Gas', '6.00');
insert into produto (cod_produto, nome, preço) values (22, 'Frappuccino', '8.40');
insert into produto (cod_produto, nome, preço) values (23, 'Brownie', '8.85');
insert into produto (cod_produto, nome, preço) values (24, 'Cookie', '6.20');
insert into produto (cod_produto, nome, preço) values (25, 'Pudim', '9.00');
insert into produto (cod_produto, nome, preço) values (26, 'Donuts', '12.50');
insert into produto (cod_produto, nome, preço) values (27, 'Bolo de Chocolate', '8.90');
insert into produto (cod_produto, nome, preço) values (28, 'Bolo Comum', '4.80');
insert into produto (cod_produto, nome, preço) values (29, 'Bolo de Morango', '10.00');
insert into produto (cod_produto, nome, preço) values (30, 'Bolo de Ninho', '13.50');
insert into produto (cod_produto, nome, preço) values (31, 'Bolo de Nutella', '13.90');
insert into produto (cod_produto, nome, preço) values (32, 'Macarons', '9.00');
insert into produto (cod_produto, nome, preço) values (33, 'Torta de Limão', '8.80');
insert into produto (cod_produto, nome, preço) values (34, 'Empada', '6.60');
insert into produto (cod_produto, nome, preço) values (35, 'Coxinha', '7.90');
insert into produto (cod_produto, nome, preço) values (36, 'Quibe', '7.90');
insert into produto (cod_produto, nome, preço) values (37, 'Pastel de Forno', '6.70');
insert into produto (cod_produto, nome, preço) values (38, 'Esfiha', '6.70');
insert into produto (cod_produto, nome, preço) values (39, 'Crepe Recheado', '8.70');
insert into produto (cod_produto, nome, preço) values (40, 'Croissant', '7.90');
insert into produto (cod_produto, nome, preço) values (41, 'Joelho', '7.90');
insert into produto (cod_produto, nome, preço) values (42, 'Sanduíche Natural', '7.50');
insert into produto (cod_produto, nome, preço) values (43, 'Pizza Fatia', '9.50');
insert into produto (cod_produto, nome, preço) values (44, 'Pão de Queijo', '3.00');
insert into produto (cod_produto, nome, preço) values (45, 'Bolo Vegano', '9.80');
insert into produto (cod_produto, nome, preço) values (46, 'Salgado Vegano', '9.80');