create table produto (
	cod_produto INT,
	nome VARCHAR(50),
	preço FLOAT
);
insert into produto (cod_produto, nome, preço) values (1, 'Espresso Brasileiro', 'R$6.50');
insert into produto (cod_produto, nome, preço) values (2, 'Cappuccino', 'R$8.00');
insert into produto (cod_produto, nome, preço) values (3, 'Irish Coffee', 'R$8.00');
insert into produto (cod_produto, nome, preço) values (4, 'Latte Macchiato', 'R$12.50');
insert into produto (cod_produto, nome, preço) values (5, 'Mocha Duplo', 'R$12.80');
insert into produto (cod_produto, nome, preço) values (6, 'HI Especial',  'R$20.50');
insert into produto (cod_produto, nome, preço) values (7, 'Café Gelado', 'R$10.00');
insert into produto (cod_produto, nome, preço) values (8, 'Café Preto', 'R$5.00');
insert into produto (cod_produto, nome, preço) values (9, 'Café com Leite', 'R$7.00');
insert into produto (cod_produto, nome, preço) values (10, 'Café com Avelã', 'R$8.55');
insert into produto (cod_produto, nome, preço) values (11, 'Café Cremoso', 'R$9.80');
insert into produto (cod_produto, nome, preço) values (12, 'Café com Canela', 'R$7.00');
insert into produto (cod_produto, nome, preço) values (13, 'Cappuccino Italiano', 'R$18.95');
insert into produto (cod_produto, nome, preço) values (14, 'Espresso Panna', 'R$10.75');
insert into produto (cod_produto, nome, preço) values (15, 'Café Americano', 'R$7.98');
insert into produto (cod_produto, nome, preço) values (16, 'Chocolate Quente', 'R$9.00');
insert into produto (cod_produto, nome, preço) values (17, 'Leite com Caramelo', 'R$6.90');
insert into produto (cod_produto, nome, preço) values (18, 'Suco Natural', 'R$12.50');
insert into produto (cod_produto, nome, preço) values (19, 'Suco Industrializado', 'R$5.00');
insert into produto (cod_produto, nome, preço) values (20, 'Água sem Gás', 'R$4.00');
insert into produto (cod_produto, nome, preço) values (21, 'Água com Gas', 'R$6.00');
insert into produto (cod_produto, nome, preço) values (22, 'Frappuccino', 'R$8.40');
insert into produto (cod_produto, nome, preço) values (23, 'Brownie', 'R$8.85');
insert into produto (cod_produto, nome, preço) values (24, 'Cookie', 'R$6.20');
insert into produto (cod_produto, nome, preço) values (25, 'Pudim', 'R$9.00');
insert into produto (cod_produto, nome, preço) values (26, 'Donuts', 'R$12.50');
insert into produto (cod_produto, nome, preço) values (27, 'Bolo de Chocolate', 'R$8.90');
insert into produto (cod_produto, nome, preço) values (28, 'Bolo Comum', 'R$4.80');
insert into produto (cod_produto, nome, preço) values (29, 'Bolo de Morango', 'R$10.00');
insert into produto (cod_produto, nome, preço) values (30, 'Bolo de Ninho', 'R$13.50');
insert into produto (cod_produto, nome, preço) values (31, 'Bolo de Nutella', 'R$13.90');
insert into produto (cod_produto, nome, preço) values (32, 'Macarons', 'R$9.00');
insert into produto (cod_produto, nome, preço) values (33, 'Torta de Limão', 'R$8.80');
insert into produto (cod_produto, nome, preço) values (34, 'Empada', 'R$6.60');
insert into produto (cod_produto, nome, preço) values (35, 'Coxinha', 'R$7.90');
insert into produto (cod_produto, nome, preço) values (36, 'Quibe', 'R$7.90');
insert into produto (cod_produto, nome, preço) values (37, 'Pastel de Forno', 'R$6.70');
insert into produto (cod_produto, nome, preço) values (38, 'Esfiha', 'R$6.70');
insert into produto (cod_produto, nome, preço) values (39, 'Crepe Recheado', 'R$8.70');
insert into produto (cod_produto, nome, preço) values (40, 'Croissant', 'R$7.90');
insert into produto (cod_produto, nome, preço) values (41, 'Joelho', 'R$7.90');
insert into produto (cod_produto, nome, preço) values (42, 'Sanduíche Natural', 'R$7.50');
insert into produto (cod_produto, nome, preço) values (43, 'Pizza Fatia', 'R$9.50');
insert into produto (cod_produto, nome, preço) values (44, 'Pão de Queijo', 'R$3.00');
insert into produto (cod_produto, nome, preço) values (45, 'Bolo Vegano', 'R$9.80');
insert into produto (cod_produto, nome, preço) values (46, 'Salgado Vegano', 'R$9.80');