create table produto (
	nome VARCHAR(50),
	preço FLOAT
);
insert into produto (nome, preço) values ('Espresso Brasileiro', 'R$6.50');
insert into produto (nome, preço) values ('Cappuccino', 'R$8.00');
insert into produto (nome, preço) values ('Irish Coffee', 'R$8.00');
insert into produto (nome, preço) values ('Latte Macchiato', 'R$12.50');
insert into produto (nome, preço) values ('Mocha Duplo', 'R$12.80');
insert into produto (nome, preço) values ('HI Especial', 'R$20.50');
insert into produto (nome, preço) values ('Café Gelado', 'R$10.00');
insert into produto (nome, preço) values ('Café Preto', 'R$5.00');
insert into produto (nome, preço) values ('Café com Leite', 'R$7.00');
insert into produto (nome, preço) values ('Café com Avelã', 'R$8.55');
insert into produto (nome, preço) values ('Café Cremoso', 'R$9.80');
insert into produto (nome, preço) values ('Café com Canela', 'R$7.00');
insert into produto (nome, preço) values ('Cappuccino Italiano', 'R$18.95');
insert into produto (nome, preço) values ('Espresso Panna', 'R$10.75');
insert into produto (nome, preço) values ('Café Americano', 'R$7.60');
insert into produto (nome, preço) values ('Chocolate Quente', 'R$9.00');
insert into produto (nome, preço) values ('Leite com Caramelo', 'R$6.90');
insert into produto (nome, preço) values ('Suco Natural', 'R$12.00');
insert into produto (nome, preço) values ('Suco Industrializado', 'R$5.00');
insert into produto (nome, preço) values ('Água sem Gás', 'R$4.00');
insert into produto (nome, preço) values ('Água com Gas', 'R$5.00');
insert into produto (nome, preço) values ('Frappuccino', 'R$9.75');
insert into produto (nome, preço) values ('Brownie', 'R$8.90');
insert into produto (nome, preço) values ('Cookie', 'R$6.20');
insert into produto (nome, preço) values ('Pudim', 'R$7.50');
insert into produto (nome, preço) values ('Donuts', 'R$12.00');
insert into produto (nome, preço) values ('Bolo de Chocolate', 'R$8.90');
insert into produto (nome, preço) values ('Bolo Comum', 'R$4.60');
insert into produto (nome, preço) values ('Bolo de Morango', 'R$9.90');
insert into produto (nome, preço) values ('Bolo de Ninho', 'R$11.70');
insert into produto (nome, preço) values ('Bolo de Nutella', 'R$12.90');
insert into produto (nome, preço) values ('Macarons', 'R$9.00');
insert into produto (nome, preço) values ('Torta de Limão', 'R$8.00');
insert into produto (nome, preço) values ('Empada', 'R$6.30');
insert into produto (nome, preço) values ('Coxinha', 'R$7.50');
insert into produto (nome, preço) values ('Quibe', 'R$7.50');
insert into produto (nome, preço) values ('Pastel de Forno', 'R$6.50');
insert into produto (nome, preço) values ('Esfiha', 'R$6.50');
insert into produto (nome, preço) values ('Crepe Recheado', 'R$8.00');
insert into produto (nome, preço) values ('Croissant', 'R$7.50');
insert into produto (nome, preço) values ('Joelho', 'R$7.50');
insert into produto (nome, preço) values ('Sanduíche Natural', 'R$7.00');
insert into produto (nome, preço) values ('Pizza Fatia', 'R$9.50');
insert into produto (nome, preço) values ('Pão de Queijo', 'R$3.00');
insert into produto (nome, preço) values ('Bolo Vegano', 'R$9.80');
insert into produto (nome, preço) values ('Salgado Vegano', 'R$9.80');